name: C/C++ CI

on: [push, pull_request]  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      run: |
        pip3 install conan
        conan profile detect --force

    - name: Install dependencies
      run: conan install . --output-folder=build
        
    - name: Build
      run: |
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        cmake --build .

    - name: Test
      run: |
        cd build
        ctest --rerun-failed --output-on-failure