name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y libgtest-dev cmake

    - name: Build
      run: |
        cd build
        cmake ..
        cmake --build

    - name: Test
      run: |
        cd build
        ctest .
